config/routes.rb
Rails.application.routes.draw do
  get 'amiigos', to: 'amiigos#index'
  get 'about', to: 'amiigos#about', as: 'about_amiigos'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  resources :amiibos

  scope '/checkout' do

    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'

  end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "amiigos#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    can :read, :all #permission for every user, even if not logged in

      user ||= User.new
    
      if user.seller_role? # additional permissions for logged in users
        can :manage, Amiibo, user_id: user.id
        can :manage, User, user_id: user.id
      end

      if user.admin_role?
        can :manage, :all
      end

      if user.customer_role?
        can :access, Amiibo
        can :manage, User, user_id: user.id
      end 

  end 

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/amiibo.rb
class Amiibo < ApplicationRecord
    belongs_to :user
    validates :amibo_name, :amibo_price, :description, :amibo_type, :amibo_game_series, :amibo_condition, :image, presence: true
    validates :amibo_price, numericality: {greater_than_or_equal_to: 0}
    attribute :amibo_price, default: 0.5

    has_one_attached :image, dependent: :purge
    has_rich_text :description

    self.per_page = 2
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :amiibos, dependent: :destroy

  # after_create :send_admin_mail

  # def send_admin_mail
  #   UserMailer.send_welcome_email(self).deliver_later
  # end 
end

app/controllers/amiibos_controller.rb
class AmiibosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_amiibo, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource


  # GET /amiibos
  # GET /amiibos.json
  def index
    @amiibos = Amiibo.paginate(page: params[:page])
  end

  # GET /amiibos/1
  # GET /amiibos/1.json
  def show
  end

  # GET /amiibos/new
  def new
    @amiibo = Amiibo.new
  end

  # GET /amiibos/1/edit
  def edit
  end

  # POST /amiibos
  # POST /amiibos.json
  def create
    @amiibo = Amiibo.new(amiibo_params)
    @amiibo.user_id = current_user.id

    respond_to do |format|
      if @amiibo.save
        format.html { redirect_to @amiibo, notice: 'Amiibo was successfully created.' }
        format.json { render :show, status: :created, location: @amiibo }
      else
        format.html { render :new }
        format.json { render json: @amiibo.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /amiibos/1
  # PATCH/PUT /amiibos/1.json
  def update
    respond_to do |format|
      if @amiibo.update(amiibo_params)
        format.html { redirect_to @amiibo, notice: 'Amiibo was successfully updated.' }
        format.json { render :show, status: :ok, location: @amiibo }
      else
        format.html { render :edit }
        format.json { render json: @amiibo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amiibos/1
  # DELETE /amiibos/1.json
  def destroy
    @amiibo.destroy
    respond_to do |format|
      format.html { redirect_to amiibos_url, notice: 'Amiibo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amiibo
      @amiibo = Amiibo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def amiibo_params
      params.require(:amiibo).permit(:amibo_name, :amibo_type, :amibo_price, :amibo_game_series, :amibo_condition, :image, :description)
    end
end

app/controllers/amiigos_controller.rb
class AmiigosController < ApplicationController
  def index
  end

  def about
  end 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :firstname, :lastname, :phone_number, :address, :postcode, :state, :country, :customer_role, :seller_role])
    end

end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

    def create
        
        amiibo = Amiibo.find(params[:id])

        if amiibo.nil?
            redirect_to root_path
            return
        end 

        #set up stripe session for payment
        Stripe.api_key = ENV['SECRET_KEY']
        @session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            line_items: [{
                    name: amiibo.amibo_name,
                    amount: (amiibo.amibo_price * 100).to_i,
                    currency: 'aud',
                    quantity: 1
                }],
            success_url: checkout_success_url,
            cancel_url: checkout_cancel_url
        )
        respond_to do |format|
            format.js #render create.js.erb
        end 

    end 

    def success   
    end 

    def cancel
    end 

end

app/helpers/amiibos_helper.rb
module AmiibosHelper
end

app/helpers/amiigos_helper.rb
module AmiigosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def author_of(resource)
        user_signed_in? && resource.user_id == current_user.id
    end

    #confirm user signed in is admin
    def admin_confirmed
        user_signed_in? && current_user.admin_role?
    end  

    #confirm user signed in is seller
    def seller_confirmed
        user_signed_in? && current_user.seller_role?
    end 

    #confirm used signed in is customer 
    def customer_confirmed
        user_signed_in? && current_user.customer_role?
    end 
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/amiibos/_card.html.erb
<% @amiibos.each do |amiibo| %>
    <div class="col-sm">
      <%= cl_image_tag(amiibo.image.key, crop: :scale, width: 100, cloud_name: 'prats')%>
      <h4><%= amiibo.amibo_name%></h4>
      <p>$<%= "%.2f" % amiibo.amibo_price %></p>
      <p><%= amiibo.amibo_game_series %></p>
      <button type="button" class="btn btn-secondary"> <%= link_to "View", amiibo_path(amiibo[:id]) %> </button>
    </div>
<% end %>

app/views/amiibos/_form.html.erb
<%= simple_form_for(@amiibo) do |f| %>

<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs">
  <%= f.input :amibo_name, required: true %>
  <%= f.input :amibo_type, collection: ["Case", "Figure", "Card", "Yarn"] %>
  <%= f.input :amibo_price, required: true %>
  <%= f.input :amibo_game_series, collection: ["Super Smash Bros", "Super Mario", "Super Mario Bros - 30th Anniversary", "Legend of Zelda", "Legend of Zelda - 30th Anniversary", "Splatoon", "Animal Crossing", "Yoshi's Woolly World", "Kirby", "Fire Emblem", "Metroid", "Shovel Knight", "Monster Hunter", "Skylanders", "Other"] %>
  <%= f.input :amibo_condition, collection: ["New", "Used"] %>
  <%= f.rich_text_area :description %>
  <%= f.file_field :image %>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/amiibos/edit.html.erb
<h1>Edit <%= @amiibo.amibo_name %></h1>

<%= render 'form', amiibo: @amiibo %>

<%= link_to 'Show', @amiibo %> |
<%= link_to 'Back', amiibos_path %>

app/views/amiibos/index.html.erb
<div class="main">
<h1> Amiibo Collection </h1>
  <div class="container">
    <div class="row">
      <%= render partial: "card", amiibo: @amiibo %>
    <div class="col-sm">
      <p class="pagination"> <%= will_paginate @amiibos %> </p>
    </div>
    </div>
    </div>
  </div>
</div>

app/views/amiibos/new.html.erb
<h1>New Amiibo</h1>

<%= render 'form', amiibo: @amiibo %>

<%= link_to 'Back', amiibos_path %>

app/views/amiibos/show.html.erb
<h1><%= @amiibo.amibo_name %></h1>

<p id="notice">

    <%= cl_image_tag(@amiibo.image.key, crop: :scale, width: 100, cloud_name: 'prats')%>
    <p>Price: $<%= "%.2f" % @amiibo.amibo_price %></p>
    <p>Amiibo Type:<%= @amiibo.amibo_type %></p>
    <p>Nintendo Game Series:<%= @amiibo.amibo_game_series %></p>
    <p>Product Condition:<%= @amiibo.amibo_condition %></p>
    <p>Amiibo Description:<%= @amiibo.description %></p>

<% unless author_of(@amiibo)%>
    <%= button_to 'Buy', checkout_create_path, method: :post, params: {id: @amiibo.id }, remote: true %>
<% end %>

<%= notice %> </p>
<hr>
<% if author_of(@amiibo)%>
    <%= link_to 'New Amiibo', new_amiibo_path %>
    <%= link_to 'Edit', edit_amiibo_path(@amiibo) %>
    <%= link_to "Delete!", amiibo_path(@amiibo), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %> |
<%= link_to 'Back', amiibos_path %>

app/views/amiigos/about.html.erb
<h1> Amiigo </h1>

<p> Started with my obbsession of animal crossing and wanting to collect all the rare amiibo's across the globe. As an avid lover of the nintendo universe, I wanted to create a marketplace where you can buy and sell amiibo's across the globe.
Welcome to Amiigo, your go to friend with all the amiibos. </p>

app/views/amiigos/index.html.erb
<h1> Welcome to Amiigo </h1>

<%= image_tag ("kkamiibo.jpg"), class: "homeamiibo" %>

<div class="main">
    <button type="button" class="btn btn-secondary">
        <%= link_to "About", about_amiigos_path %>
    </button>
</div>
<% if user_signed_in? %>
<div class="main">
    <button type="button" class="btn btn-secondary">
        <%= link_to "Collection", amiibos_path %>
    </button>
<% end %>
</div>

app/views/checkout/cancel.html.erb
<h1>Transaction Cancelled</h1>

<p> This transaction has not been processed. If you'd like to purchase another product:
    <%= link_to "Amiibo", amiibos_path %>
</p>

app/views/checkout/create.js.erb
var stripe = Stripe('<%= ENV['PUBLISHABLE_KEY']%>');

stripe.redirectToCheckout({
    sessionId: '<%= @session.id%>'
}).then(function(result) {

    console.log(result.error.message);
})

app/views/checkout/success.html.erb
<h1>Success</h1>
<p>You've successfully made a payment!</p>
<%= link_to "Amiibo", amiibos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amiigo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= render "shared/navbar" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand"> <%= link_to "AMIIGO", amiigos_path %> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <% if user_signed_in? %>
      <a class="nav-link active"> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %> <span class="sr-only"> (current) </span></a>
        <% if admin_confirmed %>
          <a class="nav-link active"> <%= link_to "Admin Dashboard", rails_admin_path %> </a>
        <% end %> 
      <a class="nav-link active"> <%= link_to "Edit Account", edit_user_registration_path %> </a>
      <a class="nav-link active"> <%= link_to "Amiibo Collection", amiibos_path %> </a>
      <% if seller_confirmed %>
        <a class="nav-link active"> <%= link_to "Sell Your Amiibo", new_amiibo_url %> </a>
      <%end%>
      <% else %>
        <a class="nav-link active"> <%= link_to "Sign In",  new_user_session_path %> </a>
        <a class="nav-link active"> <%= link_to "Sign Up", new_user_registration_path %> </a>
      <% end %>
    </div>
  </div>
</nav>
      
          
          
          
      
   

  
  